version: '3.4'
volumes:
  catalog-datafiles:
services:
  catalogmicroservice:
    image: ${DOCKER_REGISTRY-}catalogmicroservice
    build:
      context: .
      dockerfile: CatalogMicroservice/Dockerfile
    depends_on: 
            - catalog-database
    ports:
          - "5014:80"
          - "732:443"
    restart: always
        
    environment: 
          - DBHOST=catalog-database
          - ASPNETCORE_ENVIRONMENT=Development
      
      
  catalog-database:
        image: mysql:8.0.25
        ports:
          - "3366:3306"
        volumes:
          - catalog-datafiles:/var/lib/mysql
        restart: always
        environment: 
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: emanueld92
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: catalog
