// <auto-generated />
using System;
using CatalogMicroservice.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CatalogMicroservice.DataAccess.Migrations
{
    [DbContext(typeof(CatalogMicroserviceContext))]
    partial class CatalogMicroserviceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("CatalogMicroservice.Core.Entity.Category", b =>
                {
                    b.Property<int>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NameCategory")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdCategory");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CatalogMicroservice.Core.Entity.Make", b =>
                {
                    b.Property<int>("IdMake")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MakeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdMake");

                    b.ToTable("Makes");
                });

            modelBuilder.Entity("CatalogMicroservice.Core.Entity.Product", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CategoryIdCategory")
                        .HasColumnType("int");

                    b.Property<int?>("MakeIdMake")
                        .HasColumnType("int");

                    b.Property<string>("NameProduct")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdProduct");

                    b.HasIndex("CategoryIdCategory");

                    b.HasIndex("MakeIdMake");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CatalogMicroservice.Core.Entity.Product", b =>
                {
                    b.HasOne("CatalogMicroservice.Core.Entity.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryIdCategory");

                    b.HasOne("CatalogMicroservice.Core.Entity.Make", "Make")
                        .WithMany()
                        .HasForeignKey("MakeIdMake");

                    b.Navigation("Category");

                    b.Navigation("Make");
                });
#pragma warning restore 612, 618
        }
    }
}
