version: '3.4'
volumes:
  catalog-datafiles:
  seller-datafiles:
services:
#Catalog MicroServices
  catalogmicroservice:
    image: ${DOCKER_REGISTRY-}catalogmicroservice
    build:
      context: .
      dockerfile: CatalogMicroservice/Dockerfile
    depends_on: 
            - catalog-database
    ports:
          - "5014:80"
          - "732:443"
    restart: always
        
    environment: 
          - DBHOST=catalog-database
          - ASPNETCORE_ENVIRONMENT=Development
 
#Seller MicroService          
  sellermicroservice:
    image: ${DOCKER_REGISTRY-}microservicioventas
    build:
      context: .
      dockerfile: MicroservicioVentas/Dockerfile
    depends_on: 
            - seller-database
    ports:
          - "5015:80"
          - "733:443"
    restart: always
        
    environment: 
          - DBHOST=seller-database
          - ASPNETCORE_ENVIRONMENT=Development
      

#Db Catalgo
  catalog-database:
        image: mysql:8.0.25
        ports:
          - "3366:3306"
        volumes:
          - catalog-datafiles:/var/lib/mysql
        restart: always
        environment: 
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: emanueld92
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: catalog

#Db Seller
  seller-database:
        image: mysql:8.0.25
        ports:
          - "3367:3306"
        volumes:
          - seller-datafiles:/var/lib/mysql
        restart: always
        environment: 
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: ismaelroot
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: seller
